# Generated by Django 5.2.14 on 2026-06-05

from django.db import migrations, models


def add_preferred_learning_style_if_missing(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    table_name = UserProfile._meta.db_table
    column_name = "preferred_learning_style"

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        }

    if column_name in existing_columns:
        return

    field = models.CharField(max_length=30, blank=True, null=True)
    field.set_attributes_from_name(column_name)
    schema_editor.add_field(UserProfile, field)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_topic_userprofile_userinteresttopic_seed_topics"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_preferred_learning_style_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="userprofile",
                    name="preferred_learning_style",
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ("theory", "이론 중심"),
                            ("practice", "실습 중심"),
                            ("project", "프로젝트 중심"),
                            ("video", "영상 강의 중심"),
                            ("text", "문서/책 중심"),
                            ("balanced", "균형형"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
