# Generated by Django 5.2.14 on 2026-06-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_topic_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=150)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('alias_type', models.CharField(blank=True, max_length=50)),
                ('match_policy', models.CharField(blank=True, max_length=50)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='accounts.topic')),
            ],
            options={
                'db_table': 'topic_aliases',
                'unique_together': {('topic', 'alias_name', 'match_policy')},
            },
        ),
    ]
