# Generated by Django 5.2.14 on 2026-06-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_topicalias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_type',
            field=models.CharField(choices=[('domain', 'Domain'), ('subject', 'Subject'), ('concept', 'Concept'), ('skill', 'Skill')], default='skill', max_length=30),
        ),
    ]
