# Generated by Django 5.2.14 on 2026-06-05 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_userprofile_preferred_learning_style'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('learning_objective', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('source_row_number', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum_courses',
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_resources',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_session', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('goal', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=30)),
                ('target_weeks', models.PositiveSmallIntegerField(default=8)),
                ('weekly_available_hours', models.PositiveSmallIntegerField(default=7)),
                ('difficulty_level', models.CharField(default='beginner', max_length=30)),
                ('preferred_learning_style', models.CharField(default='balanced', max_length=30)),
                ('recommendation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'curricula',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CurriculumStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(default='beginner', max_length=30)),
                ('estimated_hours', models.PositiveSmallIntegerField(default=0)),
                ('prerequisite_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='curriculum.curriculum')),
                ('target_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_steps', to='accounts.topic')),
            ],
            options={
                'db_table': 'curriculum_steps',
                'ordering': ('step_order', 'id'),
                'unique_together': {('curriculum', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_categories', to='curriculum.category')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_categories', to='curriculum.curriculum')),
            ],
            options={
                'db_table': 'curriculum_categories',
                'unique_together': {('curriculum', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topics', to='accounts.topic')),
                ('curriculum_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topics', to='curriculum.curriculumcourse')),
            ],
            options={
                'db_table': 'course_topics',
                'unique_together': {('curriculum_course', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumStepCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('curriculum_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_step_courses', to='curriculum.curriculumcourse')),
                ('curriculum_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_courses', to='curriculum.curriculumstep')),
            ],
            options={
                'db_table': 'curriculum_step_courses',
                'unique_together': {('curriculum_step', 'curriculum_course')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumStepResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('curriculum_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_resources', to='curriculum.curriculumstep')),
                ('learning_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_step_resources', to='curriculum.learningresource')),
            ],
            options={
                'db_table': 'curriculum_step_resources',
                'unique_together': {('curriculum_step', 'learning_resource')},
            },
        ),
        migrations.CreateModel(
            name='ResourceTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_topics', to='curriculum.learningresource')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_topics', to='accounts.topic')),
            ],
            options={
                'db_table': 'resource_topics',
                'unique_together': {('learning_resource', 'topic')},
            },
        ),
    ]
