# Generated by Django 5.2.14 on 2026-06-06 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_repair_missing_curriculum_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_curricula', to='curriculum.curriculumstep'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='department_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='semester',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='university_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='difficulty_level',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='provider_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30),
        ),
        migrations.CreateModel(
            name='CurriculumStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='NOT_STARTED', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_rate', models.PositiveSmallIntegerField(default=0)),
                ('actual_minutes', models.PositiveIntegerField(default=0)),
                ('last_studied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progresses', to='curriculum.curriculum')),
                ('curriculum_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='curriculum.curriculumstep')),
            ],
            options={
                'db_table': 'curriculum_step_progresses',
                'unique_together': {('curriculum', 'curriculum_step')},
            },
        ),
        migrations.CreateModel(
            name='LearningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.PositiveSmallIntegerField(default=1)),
                ('sequence_no', models.PositiveSmallIntegerField(default=1)),
                ('scheduled_date', models.DateField()),
                ('planned_hours', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed'), ('RESCHEDULED', 'Rescheduled')], default='PLANNED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_schedules', to='curriculum.curriculumstep')),
                ('step_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='curriculum.curriculumstepprogress')),
            ],
            options={
                'db_table': 'learning_schedules',
                'ordering': ('scheduled_date', 'sequence_no', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PARTIAL', 'Partial')], default='COMPLETED', max_length=30)),
                ('actual_minutes', models.PositiveIntegerField(default=0)),
                ('progress_rate', models.PositiveSmallIntegerField(default=0)),
                ('studied_at', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progresses', to='curriculum.curriculumstep')),
                ('step_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_progresses', to='curriculum.curriculumstepprogress')),
                ('learning_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_progresses', to='curriculum.learningschedule')),
            ],
            options={
                'db_table': 'learning_progresses',
                'ordering': ('-studied_at', '-id'),
            },
        ),
    ]
