# Generated by Django 5.2.14 on 2026-06-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_curriculum_completed_at_curriculum_current_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='extraction_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='link_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='match_types',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='matched_fields',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='relevance_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='lookup_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='resourcetopic',
            name='extraction_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resourcetopic',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcetopic',
            name='link_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resourcetopic',
            name='match_types',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourcetopic',
            name='matched_fields',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourcetopic',
            name='relevance_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
