# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0004_coursetopic_extraction_method_coursetopic_is_primary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningprogress",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In progress"),
                    ("PAUSED", "Paused"),
                    ("COMPLETED", "Completed"),
                    ("PARTIAL", "Partial"),
                ],
                default="COMPLETED",
                max_length=30,
            ),
        ),
    ]
