# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0005_expand_learning_progress_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="instructor_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
