"""Small sample Topic Catalog for Node 1 verification."""

from __future__ import annotations

SAMPLE_TOPIC_CATALOG: list[dict] = [
    {
        "id": 1,
        "slug": "computer-science",
        "name": "컴퓨터공학",
        "parent_slug": None,
        "depth": 1,
        "topic_type": "domain",
        "is_learning_unit": False,
        "is_assessable": False,
        "aliases": ["CS", "Computer Science"],
    },
    {
        "id": 2,
        "slug": "artificial-intelligence",
        "name": "인공지능",
        "parent_slug": "computer-science",
        "depth": 2,
        "topic_type": "field",
        "is_learning_unit": True,
        "is_assessable": True,
        "aliases": ["AI", "Artificial Intelligence"],
    },
    {
        "id": 3,
        "slug": "machine-learning",
        "name": "머신러닝",
        "parent_slug": "artificial-intelligence",
        "depth": 3,
        "topic_type": "topic",
        "is_learning_unit": True,
        "is_assessable": True,
        "aliases": ["기계학습", "Machine Learning", "ML"],
    },
    {
        "id": 4,
        "slug": "deep-learning",
        "name": "딥러닝",
        "parent_slug": "artificial-intelligence",
        "depth": 3,
        "topic_type": "topic",
        "is_learning_unit": True,
        "is_assessable": True,
        "aliases": ["Deep Learning", "DL"],
    },
    {
        "id": 5,
        "slug": "data-structures",
        "name": "자료구조",
        "parent_slug": "computer-science",
        "depth": 2,
        "topic_type": "topic",
        "is_learning_unit": True,
        "is_assessable": True,
        "aliases": ["Data Structures"],
    },
    {
        "id": 6,
        "slug": "algorithms",
        "name": "알고리즘",
        "parent_slug": "computer-science",
        "depth": 2,
        "topic_type": "topic",
        "is_learning_unit": True,
        "is_assessable": True,
        "aliases": ["Algorithm"],
    },
    {
        "id": 7,
        "slug": "database",
        "name": "데이터베이스",
        "parent_slug": "computer-science",
        "depth": 2,
        "topic_type": "topic",
        "is_learning_unit": True,
        "is_assessable": True,
        "aliases": ["DB", "Database", "SQL"],
    },
    {
        "id": 8,
        "slug": "backend-development",
        "name": "백엔드 개발",
        "parent_slug": "computer-science",
        "depth": 2,
        "topic_type": "field",
        "is_learning_unit": True,
        "is_assessable": True,
        "aliases": ["Backend", "서버 개발"],
    },
    {
        "id": 9,
        "slug": "frontend-development",
        "name": "프론트엔드 개발",
        "parent_slug": "computer-science",
        "depth": 2,
        "topic_type": "field",
        "is_learning_unit": True,
        "is_assessable": True,
        "aliases": ["Frontend", "웹 프론트엔드"],
    },
    {
        "id": 10,
        "slug": "python",
        "name": "Python",
        "parent_slug": "computer-science",
        "depth": 2,
        "topic_type": "language",
        "is_learning_unit": True,
        "is_assessable": True,
        "aliases": ["파이썬"],
    },
]

